version: "3.9"

services:
  backend:
    build: ./backend
    container_name: arrangeme-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/arrangeme
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: arrangeme-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: arrangeme
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
